### ISSUE TITLE
Renombrar repositorio.

### ISSUE THREAD

**Issue by JohnKun136NVCP** [Athenas-Marlene-GM/iOS-B-sico#1]
Una sugerencia ya que se va llevar a cabo el curso de iOS es llamarlo como curso de iOS y ahí englobarlo como iOS básico y iOS intermedio.

**Comment by Athenas-Marlene-GM** [comment]
Ya ni modo XD

**Comment by JohnKun136NVCP** [comment]
F

**Comment by Athenas-Marlene-GM** [comment]
Así es XD jajaja, bueno lo voy a pensar

**Comment by JohnKun136NVCP** [comment]
Jaja vale, entonces deja cierro el issue
